# Generated by Django 2.2.6 on 2019-10-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=128)),
                ('isTaskComplete', models.BooleanField(default=False)),
                ('noteTitle', models.CharField(max_length=64)),
                ('noteContent', models.CharField(max_length=10000)),
                ('eventName', models.CharField(max_length=64)),
                ('eventDesc', models.CharField(max_length=512)),
                ('eventDate', models.DateField()),
            ],
        ),
    ]
